# Generated by Django 4.2.7 on 2025-09-18 16:51

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_applications', models.PositiveIntegerField(default=0)),
                ('active_applications', models.PositiveIntegerField(default=0)),
                ('interviews_scheduled', models.PositiveIntegerField(default=0)),
                ('offers_received', models.PositiveIntegerField(default=0)),
                ('offers_accepted', models.PositiveIntegerField(default=0)),
                ('applications_rejected', models.PositiveIntegerField(default=0)),
                ('response_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('interview_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('offer_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('average_response_time_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('average_process_time_days', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('top_companies', models.JSONField(blank=True, default=list)),
                ('top_positions', models.JSONField(blank=True, default=list)),
                ('application_sources', models.JSONField(blank=True, default=dict)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'application_analytics',
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('resume', 'Resume'), ('cover_letter', 'Cover Letter'), ('portfolio', 'Portfolio'), ('transcript', 'Transcript'), ('certificate', 'Certificate'), ('reference_letter', 'Reference Letter'), ('writing_sample', 'Writing Sample'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_url', models.URLField(blank=True, help_text='URL to the document file')),
                ('content', models.TextField(blank=True, help_text='Text content of the document')),
                ('version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'application_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('application_submitted', 'Application Submitted'), ('acknowledgment_received', 'Acknowledgment Received'), ('phone_screen_scheduled', 'Phone Screen Scheduled'), ('phone_screen_completed', 'Phone Screen Completed'), ('technical_interview_scheduled', 'Technical Interview Scheduled'), ('technical_interview_completed', 'Technical Interview Completed'), ('final_interview_scheduled', 'Final Interview Scheduled'), ('final_interview_completed', 'Final Interview Completed'), ('offer_received', 'Offer Received'), ('offer_negotiated', 'Offer Negotiated'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('rejection_received', 'Rejection Received'), ('follow_up_sent', 'Follow-up Sent'), ('reference_requested', 'Reference Requested'), ('background_check', 'Background Check'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duration for interviews/calls', null=True)),
                ('location', models.CharField(blank=True, help_text='Location or platform for interviews', max_length=255)),
                ('attendees', models.JSONField(blank=True, default=list, help_text='List of attendees/interviewers')),
                ('outcome', models.TextField(blank=True, help_text='Outcome or results of the event')),
                ('next_steps', models.TextField(blank=True, help_text='Next steps or action items')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'application_events',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('follow_up', 'Follow-up'), ('interview_prep', 'Interview Preparation'), ('thank_you_note', 'Thank You Note'), ('deadline', 'Application Deadline'), ('custom', 'Custom Reminder')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reminder_date', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'application_reminders',
                'ordering': ['reminder_date'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('position_title', models.CharField(max_length=255)),
                ('job_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('location', models.CharField(blank=True, max_length=255)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied'), ('under_review', 'Under Review'), ('phone_screen', 'Phone Screen'), ('technical_interview', 'Technical Interview'), ('final_interview', 'Final Interview'), ('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('applied_date', models.DateTimeField(blank=True, null=True)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('expected_response_date', models.DateTimeField(blank=True, null=True)),
                ('resume_version', models.CharField(blank=True, help_text='Version of resume used', max_length=100)),
                ('cover_letter_text', models.TextField(blank=True)),
                ('portfolio_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('referral_source', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('requirements_match', models.JSONField(blank=True, default=dict, help_text='How well the application matches job requirements')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Custom tags for organization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'job_applications',
                'ordering': ['-updated_at'],
            },
        ),
    ]
