# Generated by Django 4.2.7 on 2025-09-18 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationreminder',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='applications.jobapplication'),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='applications.jobapplication'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.jobapplication'),
        ),
        migrations.AddField(
            model_name='applicationanalytics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', 'status'], name='job_applica_user_id_8bc527_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', 'applied_date'], name='job_applica_user_id_c0bfbb_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['company_name'], name='job_applica_company_f62f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status', 'priority'], name='job_applica_status_b9f49c_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationreminder',
            index=models.Index(fields=['application', 'reminder_date'], name='application_applica_87bfad_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationreminder',
            index=models.Index(fields=['reminder_date', 'is_completed'], name='application_reminde_28d1e7_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationevent',
            index=models.Index(fields=['application', 'event_date'], name='application_applica_864b06_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationevent',
            index=models.Index(fields=['event_type'], name='application_event_t_3d3eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationdocument',
            index=models.Index(fields=['application', 'document_type'], name='application_applica_051737_idx'),
        ),
    ]
