version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=your-secret-key-change-in-production
      - DATABASE_URL=sqlite:///db.sqlite3
      - JOOBLE_API_KEY=${JOOBLE_API_KEY}
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - CORS_ALLOWED_ORIGINS=http://localhost:8000,https://localhost:8000
    volumes:
      - ./backend/job_aggregator/db.sqlite3:/app/backend/job_aggregator/db.sqlite3
      - media_volume:/app/backend/media
    restart: unless-stopped

  # Optional: PostgreSQL for production-like testing
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: nyxo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
  media_volume: