# Generated by Django 4.2.7 on 2025-09-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('work', 'Work'), ('education', 'Education'), ('certification', 'Certification'), ('project', 'Project'), ('award', 'Award'), ('other', 'Other')], default='work', max_length=20)),
                ('date_achieved', models.DateField()),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'achievements',
                'ordering': ['-date_achieved'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(blank=True, max_length=200, null=True)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'education',
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('language', 'Language'), ('soft', 'Soft Skills'), ('other', 'Other')], default='technical', max_length=20)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('desired_job_titles', models.JSONField(blank=True, default=list)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('preferred_salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('preferred_salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('remote_work_preference', models.CharField(choices=[('remote', 'Remote Only'), ('hybrid', 'Hybrid'), ('onsite', 'On-site Only'), ('flexible', 'Flexible')], default='flexible', max_length=20)),
                ('bio', models.TextField(blank=True, null=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('resume_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'work_experiences',
                'ordering': ['-start_date'],
            },
        ),
    ]
